name: "create job summary action"
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const diffBody = await fs.readFileSync("./diff_job_summary");
          const snapshotBody = await fs.readFileSync("./snapshot_job_summary");
          await core.summary
            .addHeading('CDK diff report')
            .addCodeBlock(diffBody)
            .addHeading('snapshot testing report')
            .addCodeBlock(snapshotBody)
            .write()
